#See https://aka.ms/containerfastmode to understand how Visual Studio uses this Dockerfile to build your images for faster debugging.

FROM mcr.microsoft.com/dotnet/aspnet:7.0 AS base
WORKDIR /app
EXPOSE 80
EXPOSE 443

FROM mcr.microsoft.com/dotnet/sdk:7.0 AS build
WORKDIR /src
COPY ["Server/BlazorDeck.Server.csproj", "Server/"]
COPY ["Client/BlazorDeck.Client.csproj", "Client/"]
COPY ["Shared/BlazorDeck.Shared.csproj", "Shared/"]
RUN dotnet restore "Server/BlazorDeck.Server.csproj"
COPY . .
WORKDIR "/src/Server"
RUN dotnet build "BlazorDeck.Server.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "BlazorDeck.Server.csproj" -c Release -o /app/publish /p:UseAppHost=false

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "BlazorDeck.Server.dll"]